version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'my-db'
      MYSQL_USER: 'Secure_user'
      MYSQL_PASSWORD: 'PASSWORD'
      # Root Password
      MYSQL_ROOT_PASSWORD: 'RootPassword'
    command: mysqld --innodb-buffer-pool-size=768M
    ports:
      - '3306:3306'
    expose:
      - '3306'
    #Docker volume "my-database" will be create 
    volumes: 
      - my-database:/var/lib/mysql
      
   # If you want to To mount Host path  / NFS directly 
   #volumes: 
   #   - /var/lib/mysqldatabase:/var/lib/mysql
   
# mounted volume name
volumes:
  my-database:
